#!/bin/bash
# --cert FILE.pem|-c  --endpoint|-e "http://clusterurl.:19080" "appname/svcname" true|false
fullsvcName=""
propertyValue=""
propertyName="traefik.expose"
sfAuthCertPem=""
curlCertOption=""
sfEndpointUrl='http://localhost:19080/'


# parameter checking/analysing
POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -c|--cert)
    sfAuthCertPem="$2"
    curlCertOption=" --cert ${sfAuthCertPem}"
    shift # past argument
    shift # past value
    ;;
    -e|--endpoint)
    sfEndpointUrl="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
fullsvcName="${POSITIONAL[0]}"
propertyValue="${POSITIONAL[1]}"
echo ENDPOINT  = "${sfEndpointUrl}"
echo CERT_PEM  = "${sfAuthCertPem}"
echo CURL_CERT = "${curlCertOption}"
echo SERVICE   = "${fullsvcName}"
echo PROPERTY  = "${propertyName}"
echo VALUE     = "${propertyValue}"


set -- "${POSITIONAL[@]}" # restore positional parameters

exit
#echo SET: $fullsvcName : $propertyName = $propertyValue
# curl -X PUT $endpointUrm$fullsvcName'/$/GetProperty?api-version=6.0&IncludeValues=true' \
#  -d '{ "PropertyName": "'$propertyName'" , "Value": { "Kind": "String", "Data": "'$propertyValue'" }, "CustomTypeId": "LabelType" }'

