#!/bin/bash
fullsvcName=$1
ruleName=$2

propertyName="traefik.frontend.rule."$ruleName

echo "DEL:  "$fullsvcName ":" $propertyName 

curl -X DELETE 'http://localhost:19080/Names/'$fullsvcName'/$/GetProperty?api-version=6.0&PropertyName='$propertyName

