#!/bin/bash
fullsvcName=$1
propertyName=$2

echo "DEL:  "$fullsvcName ":" $propertyName 

curl -X DELETE 'http://localhost:19080/Names/'$fullsvcName'/$/GetProperty?api-version=6.0&PropertyName='$propertyName

