################################################################
# Global configuration
################################################################

# Enable debug mode
#
# Optional
# Default: false
#
# debug = true

# Log level
#
# Optional
# Default: "ERROR"
#
# logLevel = "ERROR"

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
defaultEntryPoints = ["http", "https"]

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
    [entryPoints.http]
    address = ":8080"

	[entryPoints.https]
	address = ":8443"
		[entrypoints.https.tls]



################################################################
# Let's encrypt
################################################################
[acme]
email = "niclerc@outlook.com"
storageFile = "acme.json"
onDemand = false
onHostRule = true
entryPoint = "https"
[acme.httpChallenge]
  entryPoint = "http"


################################################################
# Web configuration backend
################################################################

# Enable web configuration backend
[web]
address = ":8088"



################################################################
# Service Fabric provider
################################################################
[serviceFabric]
clusterManagementUrl = "http://localhost:19080"
apiVersion = "3.0"
refreshSeconds = 5
