################################################################
# Global configuration
################################################################

# Enable debug mode
#
# Optional
# Default: false
#
# debug = true

# Log level
#
# Optional
# Default: "ERROR"
#
# logLevel = "ERROR"

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
defaultEntryPoints = ["http", "https"]

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]


################################################################
# Let's encrypt
################################################################
[acme]
acmeLogging = true
#comment 'caServer' to use production environment
caServer = "https://acme-staging.api.letsencrypt.org/directory"
email = "niclerc@outlook.com"
storage = "acme.json"
onDemand = false
onHostRule = true
entryPoint = "https"

  [acme.httpChallenge]
  entryPoint = "http"


################################################################
# Web configuration backend
################################################################

# Enable web configuration backend
[web]
address = ":8088"



################################################################
# Service Fabric provider
################################################################

[serviceFabric]
clusterManagementUrl = "https://spikepoclc.francecentral.cloudapp.azure.com:19080"
apiVersion = "3.0"
refreshSeconds = 5
  [serviceFabric.tls]
  ca = "redksfdev.crt"
  cert = "spikepoclc.crt"
  key = "spikepoclc.key"
  insecureskipverify = true